# @package model

# Transformer model configuration
type: transformer
num_blocks: 4
hidden_channels: 128
num_heads: 4
use_mean_pooling: true
multi_query: true
increase_hidden_channels: 1
checkpoint_blocks: false
dropout_prob: null  # null means no dropout (will use training.dropout if > 0)

