# EFP (Energy Flow Polynomial) presets
# Each preset defines a list of edge configurations for kinematic polynomials

deg3:
  # Degree 3 EFPs (5 polynomials)
  edges:
    - [[0, 1], [0, 1], [0, 1]]
    - [[0, 1], [0, 1], [1, 2]]
    - [[0, 1], [1, 2], [0, 2]]
    - [[0, 1], [1, 2], [2, 3]]
    - [[0, 1], [0, 2], [0, 3]]

