# Mixing mode: interpolate between invariant and non-invariant

runs:
  - name: alpha_0_0
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.0

  - name: alpha_0_1
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.1

  - name: alpha_0_2
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.2

  - name: alpha_0_3
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.3

  - name: alpha_0_4
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.4

  - name: alpha_0_5
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.5

  - name: alpha_0_6
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.6

  - name: alpha_0_7
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.7

  - name: alpha_0_8
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.8

  - name: alpha_0_9
    field:
      _target_: latsym.tasks.Mix
      alpha: 0.9

  - name: alpha_1_0
    field:
      _target_: latsym.tasks.Mix
      alpha: 1.0
